import { Link } from 'react-router-dom';
import heroImage from './../assets/img/final_home_img.png';
import { Button, CTA, FAQList, Icon, SectionTitle } from '../components/SiteUI';
import { faqs, projects, services } from '../data/siteData';
const Home=({onQuote,onBooking})=><main>
  <section className="home-hero"><div className="hero-shape one"/><div className="hero-shape two"/><div className="container home-hero-grid"><div className="home-hero-copy"><span className="hero-badge"><i/>Digital Technology Company · Dubai</span><h1>Digital solutions that turn <em>ambition into growth.</em></h1><p>AL-TRIUMPH helps businesses move forward with confidence through software, strategy, SEO, and creative digital marketing.</p><div className="hero-actions-new"><Button onClick={onQuote}>Start your project <Icon name="arrow"/></Button><Button to="/services" variant="outline">Explore services</Button></div><div className="hero-trust"><div><strong>14+</strong><span>Years experience</span></div><div><strong>120+</strong><span>Projects delivered</span></div><div><strong>94%</strong><span>Client satisfaction</span></div></div></div><div className="home-hero-visual"><div className="hero-image-frame"><img src={heroImage} alt="AL-TRIUMPH digital business team"/></div><div className="hero-float-card top"><span><Icon name="chart"/></span><div><small>Business impact</small><strong>Results driven</strong></div></div><div className="hero-float-card bottom"><div className="avatar-stack"><i>AK</i><i>MS</i><i>+</i></div><div><strong>Trusted partnership</strong><small>UAE and worldwide</small></div></div></div></div><div className="container capability-strip"><span>SOFTWARE</span><i/> <span>CONSULTING</span><i/> <span>PERFORMANCE</span><i/> <span>SOCIAL MEDIA</span></div></section>
  <section className="section-pad"><div className="container"><SectionTitle eyebrow="What we do" title="The expertise to solve today—and scale tomorrow." text="One connected team for strategy, creative execution, technology, and continuous improvement."/><div className="service-grid-new">{services.map((s,i)=><article className={s.featured?'service-card-new featured':'service-card-new'} key={s.id}><div className="service-head"><span><Icon name={s.icon}/></span>{s.featured&&<b>Most requested</b>}</div><small>0{i+1}</small><h3>{s.title}</h3><p>{s.description}</p><ul>{s.features.map(x=><li key={x}><Icon name="check" size={15}/>{x}</li>)}</ul><Link to={`/services/${s.id}`}>Learn more <Icon name="arrow" size={16}/></Link></article>)}</div></div></section>
  <section className="about-home section-pad"><div className="container about-home-grid"><div className="about-home-images"><img src="https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80" alt="AL-TRIUMPH team collaboration"/><div className="experience-box"><strong>14+</strong><span>years of<br/>shared experience</span></div></div><div><SectionTitle eyebrow="Why AL-TRIUMPH" title="A practical partner for meaningful digital progress."/><p>We combine creative thinking with structured execution. Every recommendation is connected to business value, every project is communicated clearly, and every solution is built to last.</p><div className="values-list">{[['shield','Dependable delivery','Clear scope, disciplined quality, and transparent progress.'],['users','Human partnership','Senior support and honest communication at every stage.'],['chart','Built for outcomes','Decisions guided by customer needs and measurable results.']].map(x=><div key={x[1]}><span><Icon name={x[0]}/></span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></div>)}</div><Button to="/about" variant="dark">Discover our company <Icon name="arrow"/></Button></div></div></section>
  <section className="section-pad projects-home"><div className="container"><div className="title-row"><SectionTitle eyebrow="Selected projects" title="Work designed to make a measurable difference."/><Button to="/projects" variant="text">View all projects <Icon name="arrow"/></Button></div><div className="project-showcase">{projects.slice(0,3).map((p,i)=><Link to="/projects" className={`project-tile ${i===0?'large':''}`} key={p.id}><img src={p.image} alt={p.title}/><div><span>{p.category}</span><h3>{p.title}</h3><p>{p.description}</p><b>{p.result}</b></div></Link>)}</div></div></section>
  <section className="section-pad process-home"><div className="container"><SectionTitle eyebrow="Simple process" title="From first conversation to lasting impact." text="A collaborative process designed to keep decisions clear and momentum high." center/><div className="process-steps">{[['01','Discover','Understand your business, audience, and opportunity.'],['02','Plan','Shape the right strategy, scope, and success measures.'],['03','Create','Design, build, test, and improve with you.'],['04','Grow','Launch confidently and optimize from real insight.']].map((x,i)=><article key={x[0]}><span>{x[0]}</span>{i<3&&<i/>}<h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
  <section className="testimonial-home section-pad"><div className="container testimonial-grid"><div><SectionTitle eyebrow="Client experience" title="Trusted by teams that expect more."/><div className="rating-line"><strong>4.9</strong><span>★★★★★<small>Average client rating</small></span></div></div><blockquote><div className="quote-mark">“</div><p>AL-TRIUMPH brought structure, creativity, and real commercial focus to our digital transformation. Communication was excellent from day one.</p><footer><span>SK</span><div><strong>Sarah Khan</strong><small>Managing Director · Verified customer</small></div></footer></blockquote></div></section>
  <section className="section-pad faq-home"><div className="container faq-grid"><div><SectionTitle eyebrow="Frequently asked" title="Clear answers before we begin."/><p>Still have a question? Our team is ready to help.</p><div className="hero-actions-new"><Button to="/faq" variant="outline">View all FAQs</Button><Button to="/contact" variant="text">Contact support <Icon name="arrow"/></Button></div></div><FAQList items={faqs.slice(0,4)}/></div></section>
  <CTA onQuote={onQuote}/>
  <button className="whatsapp-float" aria-label="Contact AL-TRIUMPH on WhatsApp" onClick={onBooking}><span>◉</span><b>Chat with us</b></button>
</main>;export default Home;
